# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: 
        - main
  pull_request:
    branches: 
        - main

#permissions:
 # contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # check out code from repository
    - name: Check out codes
      uses: actions/checkout@v4

    #set up python environment
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    # install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run the tests
    - name: Test with pytest
      run: |
        pytest
